"""

The Syracuse (also called Collatz or Hailstone) sequence is
generated by starting with a natural number and repeatedly
applying the following function until reaching 1:
syr(x) = 1/2 if x is even; and
syr(x) = 3x + 1 if x is odd
For example, the Syracuse sequence starting with 5 is: 5, 16, 8, 4, 2, 1.
Use of inbuilt function or math library is not allowed.
This sequence will always go to 1 for every possible starting value.
Write a program that
1.Gets a star ng value from the user
2.Prints the Syracuse sequence for that star ng value.

"""

def syr(x):

    if x % 2 == 0:
        return int(x/2)
    else:
        return int(3 * x + 1)


n = int(input("Enter number: "))

lst = []

while True:
    lst.append(syr(n))
    if lst[-1] == 1:
        break
    else:
        n = lst[-1]

print(lst)